package mime

// Top-level media types.
const (
	Application = "application"
	Audio       = "audio"
	Example     = "example"
	Font        = "font"
	Haptics     = "haptics"
	Image       = "image"
	Message     = "message"
	Model       = "model"
	Multipart   = "multipart"
	Text        = "text"
	Video       = "video"
)

const UnknownMimeType Type = "unknown/unknown"

const AllMimeTypes = "*/*"

// Application Media Types
// See: https://www.iana.org/assignments/media-types/media-types.xhtml#application
// NOTE: not a comprehensive list of all application media types.
const (
	ApplicationAll                       Type = "application/*"
	ApplicationActiveMessage             Type = "application/activemessage"
	ApplicationActivityJSON              Type = "application/activity+json"
	ApplicationAppleFile                 Type = "application/applefile"
	ApplicationAtomXML                   Type = "application/atom+xml"
	ApplicationAuthPolicyXML             Type = "application/auth-policy+xml"
	ApplicationCalendarJSON              Type = "application/calendar+json"
	ApplicationCalendarXML               Type = "application/calendar+xml"
	ApplicationDNS                       Type = "application/dns"
	ApplicationDNSJSON                   Type = "application/dns+json"
	ApplicationDNSMessage                Type = "application/dns-message"
	ApplicationEmotionML                 Type = "application/emotionml+xml"
	ApplicationEPUB                      Type = "application/epub+zip"
	ApplicationExpress                   Type = "application/express"
	ApplicationGeoJSON                   Type = "application/geo+json"
	ApplicationGeoJSONSeq                Type = "application/geo+json-seq"
	ApplicationGeoFeed                   Type = "application/geofeed+csv"
	ApplicationGeoPackage                Type = "application/geopackage+sqlite3"
	ApplicationGzip                      Type = "application/gzip"
	ApplicationH224                      Type = "application/h224"
	ApplicationHTTP                      Type = "application/http"
	ApplicationJavaArchive               Type = "application/java-archive"
	ApplicationJSON                      Type = "application/json"
	ApplicationJSONSeq                   Type = "application/json-seq"
	ApplicationJSONPath                  Type = "application/jsonpath"
	ApplicationJWKJSON                   Type = "application/jwk+json"
	ApplicationJWKSetJSON                Type = "application/jwk-set+json"
	ApplicationJWKSetJWT                 Type = "application/jwk-set+jwt"
	ApplicationManifest                  Type = "application/manifest+json"
	ApplicationMathematica               Type = "application/mathematica"
	ApplicationMathML                    Type = "application/mathml+xml"
	ApplicationMBox                      Type = "application/mbox"
	ApplicationMP21                      Type = "application/mp21"
	ApplicationMP4                       Type = "application/mp4"
	ApplicationMPEG4Generic              Type = "application/mpeg4-generic"
	ApplicationMPEG4IOD                  Type = "application/mpeg4-iod"
	ApplicationMPEG4IODXMT               Type = "application/mpeg4-iod-xmt"
	ApplicationMSWord                    Type = "application/msword"
	ApplicationMultipartCore             Type = "application/multipart-core"
	ApplicationNode                      Type = "application/node"
	ApplicationOauthAuthZReq             Type = "application/oauth-authz-req+jwt"
	ApplicationOCSPRequest               Type = "application/ocsp-request"
	ApplicationOCSPResponse              Type = "application/ocsp-response"
	ApplicationOctetStream               Type = "application/octet-stream"
	ApplicationPassport                  Type = "application/passport"
	ApplicationPDF                       Type = "application/pdf"
	ApplicationPDX                       Type = "application/pdx"
	ApplicationPEMCertificateChain       Type = "application/pem-certificate-chain"
	ApplicationPGPEncrypted              Type = "application/pgp-encrypted"
	ApplicationPGPKeys                   Type = "application/pgp-keys"
	ApplicationPGPSignature              Type = "application/pgp-signature"
	ApplicationPKCS8                     Type = "application/pkcs8"
	ApplicationPKCS8Encrypted            Type = "application/pkcs8-encrypted"
	ApplicationPKCS10                    Type = "application/pkcs10"
	ApplicationPKCS12                    Type = "application/pkcs12"
	ApplicationPKIXAttrCert              Type = "application/pkix-attr-cert"
	ApplicationPKIXCert                  Type = "application/pkix-cert"
	ApplicationPKIXCRL                   Type = "application/pkix-crl"
	ApplicationPKIXPKIPath               Type = "application/pkix-pkipath"
	ApplicationPKIXCMP                   Type = "application/pkixcmp"
	ApplicationPostScript                Type = "application/postscript"
	ApplicationProtobuf                  Type = "application/protobuf"
	ApplicationProtobufJSON              Type = "application/protobuf+json"
	ApplicationRDF                       Type = "application/rdf+xml"
	ApplicationSchemaJSON                Type = "application/schema+json"
	ApplicationSessionInfo               Type = "application/session-info"
	ApplicationSetPayment                Type = "application/set-payment"
	ApplicationSetPaymentInitiation      Type = "application/set-payment-initiation"
	ApplicationSetRegistration           Type = "application/set-registration"
	ApplicationSetRegistrationInitiation Type = "application/set-registration-initiation"
	ApplicationSGML                      Type = "application/sgml"
	ApplicationSGMLOpenCatalog           Type = "application/sgml-open-catalog"
	ApplicationSOAPFastInfoset           Type = "application/soap+fastinfoset"
	ApplicationSOAP                      Type = "application/soap+xml"
	ApplicationSparQL                    Type = "application/sparql-query"
	ApplicationSparQLResults             Type = "application/sparql-results+xml"
	ApplicationSysLogMsg                 Type = "application/syslog-msg"
	ApplicationTOML                      Type = "application/toml"
	ApplicationVCardJSON                 Type = "application/vcard+json"
	ApplicationArrowFile                 Type = "application/vnd.apache.arrow.file"
	ApplicationArrowStream               Type = "application/vnd.apache.arrow.stream"
	ApplicationParquet                   Type = "application/vnd.apache.parquet"
	ApplicationThriftBinary              Type = "application/vnd.apache.thrift.binary"
	ApplicationThriftCompact             Type = "application/vnd.apache.thrift.compact"
	ApplicationThriftJSON                Type = "application/vnd.apache.thrift.json"
	ApplicationVCardXML                  Type = "application/vcard+xml"
	ApplicationBZip3                     Type = "application/vnd.bzip3"
	ApplicationMaxmind                   Type = "application/vnd.maxmind.maxmind-db"
	ApplicationMermaid                   Type = "application/vnd.mermaid"
	ApplicationMSExcel                   Type = "application/vnd.ms-excel"
	ApplicationMSHTMLHelp                Type = "application/vnd.ms-htmlhelp"
	ApplicationMSPowerPoint              Type = "application/vnd.ms-powerpoint"
	ApplicationMSWorks                   Type = "application/vnd.ms-works"
	ApplicationMsgPack                   Type = "application/vnd.msgpack"
	ApplicationSQLite3                   Type = "application/vnd.sqlite3"
	ApplicationWASM                      Type = "application/wasm"
	ApplicationXPKIMessage               Type = "application/x-pkix-message"
	ApplicationXWWWFormURLEncoded        Type = "application/x-www-form-urlencoded"
	ApplicationX509CACert                Type = "application/x-x509-ca-cert"
	ApplicationX509CARACert              Type = "application/x-x509-ca-ra-cert"
	ApplicationX509NextCACert            Type = "application/x-x509-next-ca-cert"
	ApplicationXML                       Type = "application/xml"
	ApplicationXHTML                     Type = "application/xhtml+xml"
	ApplicationXSLT                      Type = "application/xslt+xml"
	ApplicationYAML                      Type = "application/yaml"
	ApplicationZip                       Type = "application/zip"
	ApplicationZLib                      Type = "application/zlib"
	ApplicationZStd                      Type = "application/zstd"
)

// Audio Media Types
// See: https://www.iana.org/assignments/media-types/media-types.xhtml#audio
// NOTE: not a comprehensive list of all audio media types.
const (
	AudioAll         Type = "audio/*"
	Audio3GPP        Type = "audio/3gpp"
	Audio3GPP2       Type = "audio/3gpp2"
	AudioAAC         Type = "audio/aac"
	AudioAC3         Type = "audio/ac3"
	AudioAMR         Type = "audio/amr"
	AudioBasic       Type = "audio/basic"
	AudioClearMode   Type = "audio/clearmode"
	AudioCN          Type = "audio/cn"
	AudioDAT12       Type = "audio/dat12"
	AudioDLS         Type = "audio/dls"
	AudioDV          Type = "audio/dv"
	AudioDVI4        Type = "audio/dvi4"
	AudioEVRC        Type = "audio/evrc"
	AudioEVS         Type = "audio/evs"
	AudioExample     Type = "audio/example"
	AudioFLAC        Type = "audio/flac"
	AudioFlexFEC     Type = "audio/flexfec"
	AudioMIDIClip    Type = "audio/midi-clip"
	AudioMobileXMF   Type = "audio/mobile-xmf"
	AudioMPA         Type = "audio/mpa"
	AudioMP4         Type = "audio/mp4"
	AudioMP4ALATM    Type = "audio/mp4a-latm"
	AudioMPARobust   Type = "audio/mpa-robust"
	AudioMPEG        Type = "audio/mpeg"
	AudioMPEGGeneric Type = "audio/mpeg4-generic"
	AudioOGG         Type = "audio/ogg"
	AudioOpus        Type = "audio/opus"
	AudioParityFEC   Type = "audio/parityfec"
	AudioPCMA        Type = "audio/pcma"
	AudioRTPLoopback Type = "audio/rtploopback"
	AudioRTPMIDI     Type = "audio/rtp-midi"
	AudioRTX         Type = "audio/rtx"
	AudioSofa        Type = "audio/sofa"
	AudioSoundFont   Type = "audio/soundfont"
	AudioSPMIDI      Type = "audio/sp-midi"
	AudioSpeex       Type = "audio/speex"
	AudioVDVI        Type = "audio/vdvi"
)

// Example Media Types
// See: https://www.iana.org/assignments/media-types/media-types.xhtml#example
const (
	ExampleAll     Type = "example/*"
	ExampleExample Type = "example/example"
)

// Font Media Types
// See: https://www.iana.org/assignments/media-types/media-types.xhtml#font
const (
	FontAll        Type = "font/*"
	FontCollection Type = "font/collection"
	FontOTF        Type = "font/otf"
	FontSFNT       Type = "font/sfnt"
	FontTTF        Type = "font/ttf"
	FontWOFF       Type = "font/woff"
	FontWOFF2      Type = "font/woff2"
)

// Haptics Media Types
// See: https://www.iana.org/assignments/media-types/media-types.xhtml#haptics
const (
	HapticsAll  Type = "haptics/*"
	HapticsIVS  Type = "haptics/ivs"
	HapticsHJIF Type = "haptics/hjif"
	HapticsHMPG Type = "haptics/hmpg"
)

// Image Media Types
// See: https://www.iana.org/assignments/media-types/media-types.xhtml#image
// NOTE: not a comprehensive list of all image media types.
const (
	ImageAll          Type = "image/*"
	ImageAces         Type = "image/aces"
	ImageAPNG         Type = "image/apng"
	ImageAVCI         Type = "image/avci"
	ImageAVCS         Type = "image/avcs"
	ImageAVIF         Type = "image/avif"
	ImageBMP          Type = "image/bmp"
	ImageCGM          Type = "image/cgm"
	ImageExample      Type = "image/example"
	ImageGIF          Type = "image/gif"
	ImageHEIC         Type = "image/heic"
	ImageHEICSequence Type = "image/heic-sequence"
	ImageHEIF         Type = "image/heif"
	ImageHEIFSequence Type = "image/heif-sequence"
	ImageJPEG         Type = "image/jpeg"
	ImagePNG          Type = "image/png"
	ImagePWGRaster    Type = "image/pwg-raster"
	ImageSVG          Type = "image/svg+xml"
	ImageTIFF         Type = "image/tiff"
	ImageTIFFFx       Type = "image/tiff-fx"
	ImagePhotoshop    Type = "image/vnd.adobe.photoshop"
	ImageClip         Type = "image/vnd.clip"
	ImageIcon         Type = "image/vnd.microsoft.icon"
	ImageMozillaAPNG  Type = "image/vnd.mozilla.apng"
	ImageWebP         Type = "image/webp"
	ImageWMF          Type = "image/wmf"
)

// Message Media Types
// See: https://www.iana.org/assignments/media-types/media-types.xhtml#message
// NOTE: not a comprehensive list of all message media types.
const (
	MessageAll                           Type = "message/*"
	MessageBHTTP                         Type = "message/bhttp"
	MessageCPIM                          Type = "message/cpim"
	MessageDeliveryStatus                Type = "message/delivery-status"
	MessageDispositionNotification       Type = "message/disposition-notification"
	MessageExample                       Type = "message/example"
	MessageExternalBody                  Type = "message/external-body"
	MessageFeedbackReport                Type = "message/feedback-report"
	MessageGlobal                        Type = "message/global"
	MessageGlobalDeliveryStatus          Type = "message/global-delivery-status"
	MessageGlobalDispositionNotification Type = "message/global-disposition-notification"
	MessageGlobalHeaders                 Type = "message/global-headers"
	MessageHTTP                          Type = "message/http"
	MessageIMDN                          Type = "message/imdn+xml"
	MessageMLS                           Type = "message/mls"
	MessageOHTTPChunkedReq               Type = "message/ohttp-chunked-req"
	MessageOHTTPChunkedRes               Type = "message/ohttp-chunked-res"
	MessageOHTTPReq                      Type = "message/ohttp-req"
	MessageOHTTPRes                      Type = "message/ohttp-res"
	MessagePartial                       Type = "message/partial"
	MessageRFC822                        Type = "message/rfc822"
	MessageSIP                           Type = "message/sip"
	MessageSIPFrag                       Type = "message/sipfrag"
	MessageTrackingStatus                Type = "message/tracking-status"
)

// Model Media Types
// See: https://www.iana.org/assignments/media-types/media-types.xhtml#model
// NOTE: not a comprehensive list of all model media types.
const (
	ModelAll        Type = "model/*"
	Model3MF        Type = "model/3mf"
	ModelE57        Type = "model/e57"
	ModelExample    Type = "model/example"
	ModelGLTF       Type = "model/gltf-binary"
	ModelGLTFJSON   Type = "model/gltf+json"
	ModelJT         Type = "model/jt"
	ModelIGES       Type = "model/iges"
	ModelMesh       Type = "model/mesh"
	ModelMTL        Type = "model/mtl"
	ModelObj        Type = "model/obj"
	ModelPRC        Type = "model/prc"
	ModelStep       Type = "model/step"
	ModelStepXML    Type = "model/step+xml"
	ModelStepZIP    Type = "model/step+zip"
	ModelStepXMLZip Type = "model/step-xml+zip"
	ModelSTL        Type = "model/stl"
	ModelU3D        Type = "model/u3d"
	ModelVRML       Type = "model/vrml"
	ModelX3D        Type = "model/x3d-vrml"
)

// Multipart Media Types
// See: https://www.iana.org/assignments/media-types/media-types.xhtml#multipart
const (
	MultipartAlternative   Type = "multipart/alternative"
	MultipartAppleDouble   Type = "multipart/appledouble"
	MultipartByteRanges    Type = "multipart/byteranges"
	MultipartDigest        Type = "multipart/digest"
	MultipartEncrypted     Type = "multipart/encrypted"
	MultipartExample       Type = "multipart/example"
	MultipartFormData      Type = "multipart/form-data"
	MultipartHeaderSet     Type = "multipart/header-set"
	MultipartMixed         Type = "multipart/mixed"
	MultipartMultilingual  Type = "multipart/multilingual"
	MultipartParallel      Type = "multipart/parallel"
	MultipartRelated       Type = "multipart/related"
	MultipartReport        Type = "multipart/report"
	MultipartSigned        Type = "multipart/signed"
	MultipartVoiceMessage  Type = "multipart/voice-message"
	MultipartXMixedReplace Type = "multipart/x-mixed-replace"
)

// Text Media Types
// See: https://www.iana.org/assignments/media-types/media-types.xhtml#text
// NOTE: not a comprehensive list of all text media types.
const (
	TextAll                     Type = "text/*"
	TextCacheManifest           Type = "text/cache-manifest"
	TextCalendar                Type = "text/calendar"
	TextCQL                     Type = "text/cql"
	TextCQLExpression           Type = "text/cql-expression"
	TextCQLIdentifier           Type = "text/cql-identifier"
	TextCSS                     Type = "text/css"
	TextCSV                     Type = "text/csv"
	TextCSVSchema               Type = "text/csv-schema"
	TextDNS                     Type = "text/dns"
	TextEnriched                Type = "text/enriched"
	TextExample                 Type = "text/example"
	TextHTML                    Type = "text/html"
	TextJavaScript              Type = "text/javascript"
	TextMarkdown                Type = "text/markdown"
	TextMizar                   Type = "text/mizar"
	TextN3                      Type = "text/n3"
	TextOrg                     Type = "text/org"
	TextParameters              Type = "text/parameters"
	TextPlain                   Type = "text/plain"
	TextRFC822Headers           Type = "text/rfc822-headers"
	TextRichText                Type = "text/richtext"
	TextRTF                     Type = "text/rtf"
	TextRTX                     Type = "text/rtx"
	TextSGML                    Type = "text/sgml"
	TextStrings                 Type = "text/strings"
	TextTabSeparatedValues      Type = "text/tab-separated-values"
	TextTurtle                  Type = "text/turtle"
	TextVCard                   Type = "text/vcard"
	TextGML                     Type = "text/vnd.gml"
	TextGraphVIZ                Type = "text/vnd.graphviz"
	TextLatexZ                  Type = "text/vnd.latex-z"
	TextVTT                     Type = "text/vtt"
	TextWGSL                    Type = "text/wgsl"
	TextXML                     Type = "text/xml"
	TextXMLExternalParsedEntity Type = "text/xml-external-parsed-entity"
)

// Video Media Types
// See: https://www.iana.org/assignments/media-types/media-types.xhtml#video
// NOTE: not a comprehensive list of all video media types.
const (
	VideoAll          Type = "video/*"
	Video3GPP         Type = "video/3gpp"
	Video3GPP2        Type = "video/3gpp2"
	Video3GPPTT       Type = "video/3gpp-tt"
	VideoAV1          Type = "video/av1"
	VideoBMPEG        Type = "video/bmpeg"
	VideoBT656        Type = "video/bt656"
	VideoDV           Type = "video/dv"
	VideoExample      Type = "video/example"
	VideoFFV1         Type = "video/ffv1"
	VideoH261         Type = "video/h261"
	VideoH263         Type = "video/h263"
	VideoH264         Type = "video/h264"
	VideoH265         Type = "video/h265"
	VideoH266         Type = "video/h266"
	VideoJPEG         Type = "video/jpeg"
	VideoMP4          Type = "video/mp4"
	VideoMPV          Type = "video/mpv"
	VideoMPEG         Type = "video/mpeg"
	VideoMPEG4Generic Type = "video/mpeg4-generic"
	VideoNV           Type = "video/nv"
	VideoOGG          Type = "video/ogg"
	VideoPointer      Type = "video/pointer"
	VideoQuickTime    Type = "video/quicktime"
	VideoRTPLoopback  Type = "video/rtploopback"
	VideoRTX          Type = "video/rtx"
	VideoCCTV         Type = "video/vnd.cctv"
	VideoYouTube      Type = "video/vnd.youtube.yt"
	VideoVivo         Type = "video/vnd.vivo"
	VideoVP8          Type = "video/vp8"
	VideoVP9          Type = "video/vp9"
)
