package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"

	"go.rtnl.ai/x/region"
)

const (
	Testdata = "testdata/regions.json.gz"
	Datafile = "regions.data.go"
)

func main() {
	var (
		f   *os.File
		err error
	)
	if f, err = os.Create(Datafile); err != nil {
		handleError(fmt.Errorf("could not create %s: %w", Datafile, err))
	}
	defer f.Close()

	handleError(writePreamble(f))
	handleError(writeRegionConstants(f))
	handleError(writeRegionValuesMap(f))
	handleError(writeRegionNamesMap(f))
}

func handleError(err error) {
	if err != nil {
		fmt.Fprintf(os.Stderr, "regions generation failed: %s\n", err)
		os.Exit(1)
	}
}

//===========================================================================
// Code Generation
//===========================================================================

func writePreamble(f writer) (err error) {
	// Write the preamble for the generated file
	if _, err = f.WriteString("// Code generated by go generate; DO NOT EDIT.\n"); err != nil {
		return fmt.Errorf("failed to write preamble to %s: %w", Datafile, err)
	}

	// Guess the package name based on the current directory
	content := guessPackage()
	if _, err = f.WriteString(content + "\n\n"); err != nil {
		return fmt.Errorf("failed to write package declaration to %s: %w", Datafile, err)
	}

	return nil
}

func writeRegionConstants(f writer) (err error) {
	// Open region constants variable block
	if _, err := f.WriteString("// Region constants from data files\nvar (\n"); err != nil {
		return fmt.Errorf("failed to write opening var block to %s: %w", Datafile, err)
	}

	for name, region := range iterateData {
		if _, err := fmt.Fprintf(f, "\t%s Region = %d\n", name, region.ID); err != nil {
			return fmt.Errorf("failed to write region constant to %s: %w", Datafile, err)
		}
	}

	// Close the variable block
	if _, err = f.WriteString(")\n\n"); err != nil {
		return fmt.Errorf("failed to write closing var block to %s: %w", Datafile, err)
	}

	return nil
}

func writeRegionValuesMap(f writer) (err error) {
	// Open regionValues mapping block
	if _, err = f.WriteString("// Map region names to their values\nvar regionValues = map[string]uint32{\n"); err != nil {
		return fmt.Errorf("failed to write opening regionValues block to %s: %w", Datafile, err)
	}

	for name, region := range iterateData {
		if _, err := fmt.Fprintf(f, "\t%q: %d,\n", name, region.ID); err != nil {
			return fmt.Errorf("failed to write region value mapping to %s: %w", Datafile, err)
		}
	}

	// Close the regionValues mapping block
	if _, err = f.WriteString("}\n\n"); err != nil {
		return fmt.Errorf("failed to write closing regionValues block to %s: %w", Datafile, err)
	}

	return nil
}

func writeRegionNamesMap(f writer) (err error) {
	// Open the regionNames mapping block
	if _, err = f.WriteString("// Map region values to their names\nvar regionNames = map[uint32]string{\n"); err != nil {
		return fmt.Errorf("failed to write opening regionNames block to %s: %w", Datafile, err)
	}

	for name, region := range iterateData {
		if _, err := fmt.Fprintf(f, "\t%d: %q,\n", region.ID, name); err != nil {
			return fmt.Errorf("failed to write region name mapping to %s: %w", Datafile, err)
		}
	}

	// Close the regionNames mapping block
	if _, err = f.WriteString("}\n\n"); err != nil {
		return fmt.Errorf("failed to write closing regionNames block to %s: %w", Datafile, err)
	}

	return nil
}

func guessPackage() string {
	wd, err := os.Getwd()
	handleError(err)

	return fmt.Sprintf("package %s\n", filepath.Base(wd))
}

func iterateData(yield func(name string, region *region.Info) bool) {
	var (
		err     error
		entries []os.DirEntry
	)

	if entries, err = os.ReadDir("testdata"); err != nil {
		handleError(err)
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		path := filepath.Join("testdata", entry.Name())

		var data map[string]*region.Info
		if data, err = readData(path); err != nil {
			handleError(err)
		}

		for _, pair := range sortedPairs(data) {
			if !yield(pair.K, pair.V) {
				return
			}
		}
	}
}

func readData(path string) (data map[string]*region.Info, err error) {
	var f *os.File
	if f, err = os.Open(path); err != nil {
		return nil, fmt.Errorf("could not open %s: %w", path, err)
	}
	defer f.Close()

	if err = json.NewDecoder(f).Decode(&data); err != nil {
		return nil, fmt.Errorf("could not decode JSON data: %w", err)
	}
	return data, nil
}

type pair struct {
	K string
	V *region.Info
}

func sortedPairs(data map[string]*region.Info) []pair {
	pairs := make([]pair, 0, len(data))
	for k, v := range data {
		pairs = append(pairs, pair{K: k, V: v})
	}
	sort.Slice(pairs, func(i, j int) bool {
		return pairs[i].V.ID < pairs[j].V.ID
	})
	return pairs
}

type writer interface {
	io.WriteCloser
	io.StringWriter
}
