/*
Creates gravatar URLs from email addresses with user specified options.

Gravatars are a personalized user image based on the email address of the user. They
allow applications to fetch an image of the user without having to store images locally.
All gravatars are computed based on the hash of a user's email along with some options.
This package generates those URL strings for use in other applications.

See: https://docs.gravatar.com/
*/
package gravatar

import (
	"crypto/md5"
	"encoding/hex"
	"net/url"
	"path/filepath"
	"strconv"
	"strings"
)

// Default values for gravatar options generated by this package.
const (
	DefaultSize   = 80
	DefaultImage  = "identicon"
	DefaultRating = "pg"
)

var (
	baseURL, _ = url.Parse("https://www.gravatar.com")
)

// Create a new Gravatar URL from the specified email and options.
func New(email string, opts *Options) string {
	if opts == nil {
		opts = &Options{Size: DefaultSize, DefaultImage: DefaultImage, Rating: DefaultRating}
	}

	img := Hash(email)
	if opts.FileExtension != "" {
		img += opts.FileExtension
	}

	link := baseURL.ResolveReference(&url.URL{Path: filepath.Join("avatar", img)})

	params := make(url.Values)
	if opts.Size != 0 {
		params.Set("s", strconv.Itoa(opts.Size))
	}

	if opts.DefaultImage != "" {
		params.Set("d", opts.DefaultImage)
	}

	if opts.ForceDefault {
		params.Set("f", "y")
	}

	if opts.Rating != "" {
		params.Set("r", opts.Rating)
	}

	link.RawQuery = params.Encode()
	return link.String()
}

// Hash returns the Gravatar email MD5 hex encoded hash as defined in:
// https://en.gravatar.com/site/implement/hash/
func Hash(email string) string {
	email = strings.ToLower(strings.TrimSpace(email))
	sum := md5.Sum([]byte(email))
	return hex.EncodeToString(sum[:])
}

// Options allows you to specify preferences that are added as URL query params.
type Options struct {
	// The square size of the image; an request images from 1px up to 2048px.
	Size int

	// One of 404, mp, identicon, monsterid, wavatar, retro, robohash, or blank.
	DefaultImage string

	// Force the default image to always load
	ForceDefault bool

	// Rating indicates image appropriateness, one of g, pg, r, or x.
	Rating string

	// File extension is optional, can be one of .png, .jpg, etc.
	FileExtension string
}
