package country

var iso2table = [26][26]string{
	{"", "", "", "Andorra", "United Arab Emirates", "Afghanistan", "Antigua and Barbuda", "", "Anguilla", "", "", "Albania", "Armenia", "", "Angola", "", "Antarctica", "Argentina", "American Samoa", "Austria", "Australia", "", "Aruba", "Åland Islands", "", "Azerbaijan"},
	{"Bosnia and Herzegovina", "Barbados", "", "Bangladesh", "Belgium", "Burkina Faso", "Bulgaria", "Bahrain", "Burundi", "Benin", "", "Saint Barthelemy", "Bermuda", "Brunei", "Bolivia", "", "Caribbean Netherlands", "Brazil", "Bahamas", "Bhutan", "", "Bouvet Island", "Botswana", "", "Belarus", "Belize"},
	{"Canada", "", "Cocos (Keeling) Islands", "Democratic Republic of the Congo", "", "Central African Republic", "Republic of the Congo", "Switzerland", "Ivory Coast", "", "Cook Islands", "Chile", "Cameroon", "China", "Colombia", "", "", "Costa Rica", "", "", "Cuba", "Cape Verde", "Curacao", "Christmas Island", "Cyprus", "Czechia"},
	{"", "", "", "", "Germany", "", "", "", "", "Djibouti", "Denmark", "", "Dominica", "", "Dominican Republic", "", "", "", "", "", "", "", "", "", "", "Algeria"},
	{"", "", "Ecuador", "", "Estonia", "", "Egypt", "Western Sahara", "", "", "", "", "", "", "", "", "", "Eritrea", "Spain", "Ethiopia", "", "", "", "", "", ""},
	{"", "", "", "", "", "", "", "", "Finland", "Fiji", "Falkland Islands", "", "Federated States of Micronesia", "", "Faroe Islands", "", "", "France", "", "", "", "", "", "", "", ""},
	{"Gabon", "United Kingdom", "", "Grenada", "Georgia", "French Guiana", "Guernsey", "Ghana", "Gibraltar", "", "", "Greenland", "Gambia", "Guinea", "", "Guadeloupe", "Equatorial Guinea", "Greece", "South Georgia and South Sandwich Islands", "Guatemala", "Guam", "", "Guinea-Bissau", "", "Guyana", ""},
	{"", "", "", "", "", "", "", "", "", "", "Hong Kong", "", "Heard Island and McDonald Islands", "Honduras", "", "", "", "Croatia", "", "Haiti", "Hungary", "", "", "", "", ""},
	{"", "", "", "Indonesia", "Ireland", "", "", "", "", "", "", "Israel", "Isle of Man", "India", "British Indian Ocean Territory", "", "Iraq", "Iran", "Iceland", "Italy", "", "", "", "", "", ""},
	{"", "", "", "", "Jersey", "", "", "", "", "", "", "", "Jamaica", "", "Jordan", "Japan", "", "", "", "", "", "", "", "", "", ""},
	{"", "", "", "", "Kenya", "", "Kyrgyzstan", "Cambodia", "Kiribati", "", "", "", "Comoros", "Saint Kitts and Nevis", "", "North Korea", "", "South Korea", "", "", "", "", "Kuwait", "", "Cayman Islands", "Kazakhstan"},
	{"Laos", "Lebanon", "Saint Lucia", "", "", "", "", "", "Liechtenstein", "", "Sri Lanka", "", "", "", "", "", "", "Liberia", "Lesotho", "Lithuania", "Luxembourg", "Latvia", "", "", "Libya", ""},
	{"Morocco", "", "Principality of Monaco", "Moldova", "Montenegro", "Saint Martin", "Madagascar", "Marshall Islands", "", "", "North Macedonia", "Mali", "Myanmar", "Mongolia", "Macao", "Northern Mariana Islands", "Martinique", "Mauritania", "Montserrat", "Malta", "Mauritius", "Maldives", "Malawi", "Mexico", "Malaysia", "Mozambique"},
	{"Namibia", "", "New Caledonia", "", "Niger", "Norfolk Island", "Nigeria", "", "Nicaragua", "", "", "Netherlands", "", "", "Norway", "Nepal", "", "Nauru", "", "", "Niue", "", "", "", "", "New Zealand"},
	{"", "", "", "", "", "", "", "", "", "", "", "", "Oman", "", "", "", "", "", "", "", "", "", "", "", "", ""},
	{"Panama", "", "", "", "Peru", "French Polynesia", "Papua New Guinea", "Philippines", "", "", "Pakistan", "Poland", "Saint Pierre and Miquelon", "Pitcairn Islands", "", "", "", "Puerto Rico", "Palestine", "Portugal", "", "", "Palau", "", "Paraguay", ""},
	{"Qatar", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""},
	{"", "", "", "", "Reunion", "", "", "", "", "", "", "", "", "", "Romania", "", "", "", "Serbia", "", "Russia", "", "Rwanda", "", "", ""},
	{"Saudi Arabia", "Solomon Islands", "Seychelles", "Sudan", "Sweden", "", "Singapore", "Saint Helena, Ascension and Tristan da Cunha", "Slovenia", "Svalbard", "Slovakia", "Sierra Leone", "San Marino", "Senegal", "Somalia", "", "", "Suriname", "South Sudan", "Sao Tome and Principe", "", "El Salvador", "", "Sint Maarten", "Syria", "Eswatini"},
	{"", "", "Turks and Caicos Islands", "Chad", "", "French Southern and Antarctic Lands", "Togo", "Thailand", "", "Tajikistan", "Tokelau", "East Timor", "Turkmenistan", "Tunisia", "Tonga", "", "", "Turkey", "", "Trinidad and Tobago", "", "Tuvalu", "Taiwan", "", "", "Tanzania"},
	{"Ukraine", "", "", "", "", "", "Uganda", "", "", "", "", "", "United States Minor Outlying Islands", "", "", "", "", "", "United States of America", "", "", "", "", "", "Uruguay", "Uzbekistan"},
	{"Vatican City", "", "Saint Vincent and the Grenadines", "", "Venezuela", "", "British Virgin Islands", "", "Virgin Islands", "", "", "", "", "Vietnam", "", "", "", "", "", "", "Vanuatu", "", "", "", "", ""},
	{"", "", "", "", "", "Wallis and Futuna", "", "", "", "", "", "", "", "", "", "", "", "", "Samoa", "", "", "", "", "", "", ""},
	{"", "", "", "", "", "", "", "", "", "", "Kosovo", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""},
	{"", "", "", "", "Yemen", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Mayotte", "", "", "", "", "", ""},
	{"South Africa", "", "", "", "", "", "", "", "", "", "", "", "Zambia", "", "", "", "", "", "", "", "", "", "Zimbabwe", "", "", ""},
}

var iso2map = map[string]string{
	"AF": "Afghanistan",
	"EG": "Egypt",
	"AX": "Åland Islands",
	"AL": "Albania",
	"DZ": "Algeria",
	"AS": "American Samoa",
	"AD": "Andorra",
	"AO": "Angola",
	"AI": "Anguilla",
	"AQ": "Antarctica",
	"AG": "Antigua and Barbuda",
	"GQ": "Equatorial Guinea",
	"AR": "Argentina",
	"AM": "Armenia",
	"AW": "Aruba",
	"AZ": "Azerbaijan",
	"ET": "Ethiopia",
	"AU": "Australia",
	"BS": "Bahamas",
	"BH": "Bahrain",
	"BD": "Bangladesh",
	"BB": "Barbados",
	"BY": "Belarus",
	"BE": "Belgium",
	"BZ": "Belize",
	"BJ": "Benin",
	"BM": "Bermuda",
	"BT": "Bhutan",
	"BO": "Bolivia",
	"BA": "Bosnia and Herzegovina",
	"BW": "Botswana",
	"BV": "Bouvet Island",
	"BR": "Brazil",
	"IO": "British Indian Ocean Territory",
	"BN": "Brunei",
	"BG": "Bulgaria",
	"BF": "Burkina Faso",
	"BI": "Burundi",
	"CL": "Chile",
	"CN": "China",
	"CK": "Cook Islands",
	"CR": "Costa Rica",
	"CW": "Curacao",
	"DK": "Denmark",
	"CD": "Democratic Republic of the Congo",
	"DE": "Germany",
	"DM": "Dominica",
	"DO": "Dominican Republic",
	"DJ": "Djibouti",
	"EC": "Ecuador",
	"SV": "El Salvador",
	"CI": "Ivory Coast",
	"ER": "Eritrea",
	"EE": "Estonia",
	"SZ": "Eswatini",
	"FK": "Falkland Islands",
	"FO": "Faroe Islands",
	"FJ": "Fiji",
	"FI": "Finland",
	"FM": "Federated States of Micronesia",
	"FR": "France",
	"GF": "French Guiana",
	"PF": "French Polynesia",
	"TF": "French Southern and Antarctic Lands",
	"MC": "Principality of Monaco",
	"GA": "Gabon",
	"GM": "Gambia",
	"GE": "Georgia",
	"GH": "Ghana",
	"GI": "Gibraltar",
	"GD": "Grenada",
	"GR": "Greece",
	"GL": "Greenland",
	"GP": "Guadeloupe",
	"GU": "Guam",
	"GT": "Guatemala",
	"GG": "Guernsey",
	"GN": "Guinea",
	"GW": "Guinea-Bissau",
	"GY": "Guyana",
	"HT": "Haiti",
	"HM": "Heard Island and McDonald Islands",
	"HN": "Honduras",
	"HK": "Hong Kong",
	"IN": "India",
	"ID": "Indonesia",
	"IM": "Isle of Man",
	"IQ": "Iraq",
	"IR": "Iran",
	"IE": "Ireland",
	"IS": "Iceland",
	"IL": "Israel",
	"IT": "Italy",
	"JM": "Jamaica",
	"JP": "Japan",
	"YE": "Yemen",
	"JE": "Jersey",
	"JO": "Jordan",
	"VG": "British Virgin Islands",
	"VI": "Virgin Islands",
	"KY": "Cayman Islands",
	"KH": "Cambodia",
	"CM": "Cameroon",
	"CA": "Canada",
	"CV": "Cape Verde",
	"BQ": "Caribbean Netherlands",
	"KZ": "Kazakhstan",
	"QA": "Qatar",
	"KE": "Kenya",
	"KG": "Kyrgyzstan",
	"KI": "Kiribati",
	"UM": "United States Minor Outlying Islands",
	"CC": "Cocos (Keeling) Islands",
	"CO": "Colombia",
	"KM": "Comoros",
	"XK": "Kosovo",
	"HR": "Croatia",
	"CU": "Cuba",
	"KW": "Kuwait",
	"LA": "Laos",
	"LS": "Lesotho",
	"LV": "Latvia",
	"LB": "Lebanon",
	"LR": "Liberia",
	"LY": "Libya",
	"LI": "Liechtenstein",
	"LT": "Lithuania",
	"LU": "Luxembourg",
	"MO": "Macao",
	"MG": "Madagascar",
	"MW": "Malawi",
	"MY": "Malaysia",
	"MV": "Maldives",
	"ML": "Mali",
	"MT": "Malta",
	"MA": "Morocco",
	"MH": "Marshall Islands",
	"MQ": "Martinique",
	"MR": "Mauritania",
	"MU": "Mauritius",
	"YT": "Mayotte",
	"MX": "Mexico",
	"MD": "Moldova",
	"MN": "Mongolia",
	"ME": "Montenegro",
	"MS": "Montserrat",
	"MZ": "Mozambique",
	"MM": "Myanmar",
	"NA": "Namibia",
	"NR": "Nauru",
	"NP": "Nepal",
	"NC": "New Caledonia",
	"NZ": "New Zealand",
	"NI": "Nicaragua",
	"NL": "Netherlands",
	"NE": "Niger",
	"NG": "Nigeria",
	"NU": "Niue",
	"KP": "North Korea",
	"MP": "Northern Mariana Islands",
	"MK": "North Macedonia",
	"NF": "Norfolk Island",
	"NO": "Norway",
	"OM": "Oman",
	"AT": "Austria",
	"TL": "East Timor",
	"PK": "Pakistan",
	"PS": "Palestine",
	"PW": "Palau",
	"PA": "Panama",
	"PG": "Papua New Guinea",
	"PY": "Paraguay",
	"PE": "Peru",
	"PH": "Philippines",
	"PN": "Pitcairn Islands",
	"PL": "Poland",
	"PT": "Portugal",
	"PR": "Puerto Rico",
	"CG": "Republic of the Congo",
	"RE": "Reunion",
	"RW": "Rwanda",
	"RO": "Romania",
	"RU": "Russia",
	"MF": "Saint Martin",
	"SB": "Solomon Islands",
	"ZM": "Zambia",
	"WS": "Samoa",
	"SM": "San Marino",
	"BL": "Saint Barthelemy",
	"ST": "Sao Tome and Principe",
	"SA": "Saudi Arabia",
	"SE": "Sweden",
	"CH": "Switzerland",
	"SN": "Senegal",
	"RS": "Serbia",
	"SC": "Seychelles",
	"SL": "Sierra Leone",
	"ZW": "Zimbabwe",
	"SG": "Singapore",
	"SX": "Sint Maarten",
	"SK": "Slovakia",
	"SI": "Slovenia",
	"SO": "Somalia",
	"ES": "Spain",
	"LK": "Sri Lanka",
	"SH": "Saint Helena, Ascension and Tristan da Cunha",
	"KN": "Saint Kitts and Nevis",
	"LC": "Saint Lucia",
	"PM": "Saint Pierre and Miquelon",
	"VC": "Saint Vincent and the Grenadines",
	"ZA": "South Africa",
	"SD": "Sudan",
	"GS": "South Georgia and South Sandwich Islands",
	"KR": "South Korea",
	"SS": "South Sudan",
	"SR": "Suriname",
	"SJ": "Svalbard",
	"SY": "Syria",
	"TJ": "Tajikistan",
	"TW": "Taiwan",
	"TZ": "Tanzania",
	"TH": "Thailand",
	"TG": "Togo",
	"TK": "Tokelau",
	"TO": "Tonga",
	"TT": "Trinidad and Tobago",
	"TD": "Chad",
	"CZ": "Czechia",
	"TN": "Tunisia",
	"TR": "Turkey",
	"TM": "Turkmenistan",
	"TC": "Turks and Caicos Islands",
	"TV": "Tuvalu",
	"UG": "Uganda",
	"UA": "Ukraine",
	"HU": "Hungary",
	"UY": "Uruguay",
	"UZ": "Uzbekistan",
	"VU": "Vanuatu",
	"VA": "Vatican City",
	"VE": "Venezuela",
	"AE": "United Arab Emirates",
	"US": "United States of America",
	"GB": "United Kingdom",
	"VN": "Vietnam",
	"WF": "Wallis and Futuna",
	"CX": "Christmas Island",
	"EH": "Western Sahara",
	"CF": "Central African Republic",
	"CY": "Cyprus",
}

var root2 *Trie

func init() {
	root2 = &Trie{}
	for code, country := range iso2map {
		root2.Insert(code, country)
	}
}

func Table2Lookup(code string) (string, bool) {
	if code[0] < 'A' || code[0] > 'Z' {
		return "", false
	}
	if code[1] < 'A' || code[1] > 'Z' {
		return "", false
	}
	country := iso2table[code[0]-'A'][code[1]-'A']
	return country, country != ""
}

func Map2Lookup(code string) (string, bool) {
	val, ok := iso2map[code]
	return val, ok
}

func Trie2Lookup(code string) (string, bool) {
	return root2.Find(code)
}
